
import usePosterContent from "../../hooks/usePosterContent";
import EditIcon from '../../media/Images/edit.png';
import { useNavigate } from "react-router-dom";

const fonts = [
	{
		"headingfont": "Poppins",
		"paragraphfont1": "Poppins",
		"paragraphfont2": "Poppins",
		"paragraphfont3": "Poppins"
	},
	{
		"headingfont": "Reef",
		"paragraphfont1": "Reef",
		"paragraphfont2": "Reef",
		"paragraphfont3": "Reef"
	},
	{
		"headingfont": "Action Man",
		"paragraphfont1": "morish",
		"paragraphfont2": "Action Man",
		"paragraphfont3": "Action Man"
	},
	{
		"headingfont": "Action Man Bold",
		"paragraphfont1": "Action Man Bold",
		"paragraphfont2": "Action Man Bold",
		"paragraphfont3": "Action Man"
	}
];

const templatePreview = ({ data, index1 }) => {
	const navigate = useNavigate();
	const { prompt, catagory, posterText, Title, Promotion, Contact, Description, setFont, index, setSelectedPoster } = usePosterContent();
	const handleClick=()=>{
		console.log("edit");
		setFont([fonts[index1]]);
		setSelectedPoster(index1);
		navigate("/design-editor");
	}
	return (
		<>
			<div className="z-0 hover:opacity-90 relative group">
				<div className="w-[500px] h-[500px] relative overflow-hidden rounded-lg shadow-lg cursor-pointer">
					<img className="object-cover w-full h-full" src={data.image_path} alt="Flower and sky" />
					<div className="absolute top-0 left-0 px-6 py-12">
						<div className="relative">
							<h4 style={{ "fontFamily": `${fonts[index1].headingfont}` }}
								className={`mb-3 text-[30px] font-bold tracking-tight text-gray-100 max-w-[290px]`}
							>
								{Title}
							</h4>
							<p style={{ "fontFamily": `${fonts[index1].paragraphfont1}` }}
								className={`max-w-[250px] text-sm leading-normal text-gray-100`}>
								{posterText[index]}
							</p>
						</div>
					</div>
					<div className="absolute top-[50%] left-0 px-6">
						<h4 style={{ "fontFamily": `${fonts[index1].paragraphfont2}` }}
							className={`font-extrabold text-2xl text-gray-100 `}>
							{Promotion}
						</h4>
						<p style={{ "fontFamily": `${fonts[index1].paragraphfont2}` }}
							className={`text-sm text-gray-100 `}>{Description} </p>
					</div>
					<div className="absolute bottom-2 left-0 px-6">
						<div className="relative">
							<h4 style={{ "fontFamily": `${fonts[index1].paragraphfont3}` }}
								className={`text-sm text-gray-100 max-w-[280px]`}>
								Graphic Generated By AI
							</h4>
							<p style={{ "fontFamily": `${fonts[index1].paragraphfont3}` }}
								className={`text-sm text-gray-100 max-w-[280px]`}>
								prompt: {prompt}
							</p>
						</div>
					</div>
					<div className="absolute right-0 bottom-0 p-2">
						<div className="flex items-center">
							<h4 style={{ "fontFamily": `${fonts[index1].paragraphfont3}` }}
								className={`text-[15px] text-lg font-semibold tracking-tight text-gray-100 `}>
								Contact at:
							</h4>
							<p style={{ "fontFamily": `${fonts[index1].paragraphfont3}` }}
								className={`text-[15px] text-lg font-normal text-gray-100 ml-2`}>{` ${Contact}`}</p>
						</div>
					</div>
				</div>
				<div className="z-20 absolute right-8 top-8">
					<div className="hidden group-hover:flex relative">
						<img className="absolute left-3 top-3" src={EditIcon} alt="Edit Icons" width="15px" height="15px" />
						<button className="py-2 pl-8 pr-4 text-white text-md font-roboto font-bold rounded bg-black" onClick={handleClick} >Edit</button>
					</div>
				</div>

			</div>
		</>
	)
}

export default templatePreview
