
import usePosterContent from "../../hooks/usePosterContent";
import EditIcon from '../../media/Images/edit.png';
import InstaIcon from '../../media/Images/insta.png';
import { useNavigate } from "react-router-dom";

import Preview from '../preview/index';

const fonts = [
	{
		"headingfont": "Poppins",
		"paragraphfont1": "Poppins",
		"paragraphfont2": "Poppins",
		"paragraphfont3": "Poppins"
	},
	{
		"headingfont": "Reef",
		"paragraphfont1": "Reef",
		"paragraphfont2": "Reef",
		"paragraphfont3": "Reef"
	},
	{
		"headingfont": "Action Man",
		"paragraphfont1": "morish",
		"paragraphfont2": "Action Man",
		"paragraphfont3": "Action Man"
	},
	{
		"headingfont": "Action Man Bold",
		"paragraphfont1": "Action Man Bold",
		"paragraphfont2": "Action Man Bold",
		"paragraphfont3": "Action Man"
	}
];

const templatePreview = ({ data, index1 }) => {
	const navigate = useNavigate();
	const { prompt, catagory, posterText, Title, Promotion, Contact, Description, setFont, index, setSelectedPoster } = usePosterContent();
	const handleClick = () => {
		console.log("edit");
		setFont([fonts[index1]]);
		setSelectedPoster(index1);
		navigate("/design-editor");
	}
	return (
		<>
			{/* <div className="z-0 hover:opacity-90 relative group">
				<div className="w-[500px] h-[500px] relative overflow-hidden rounded-lg shadow-lg cursor-pointer">
					<img className="object-cover w-full h-full" src={data.image_path} alt="Flower and sky" />
					<div className="absolute top-0 left-0 px-6 py-12">
						<div className="relative">
							<h4 style={{ "fontFamily": `${fonts[index1].headingfont}` }}
								className={`mb-3 text-[30px] font-bold tracking-tight text-gray-100 max-w-[290px]`}
							>
								{Title}
							</h4>
							<p style={{ "fontFamily": `${fonts[index1].paragraphfont1}` }}
								className={`max-w-[250px] text-sm leading-normal text-gray-100`}>
								{posterText[index]}
							</p>
						</div>
					</div>
					<div className="absolute top-[50%] left-0 px-6">
						<h4 style={{ "fontFamily": `${fonts[index1].paragraphfont2}` }}
							className={`font-extrabold text-2xl text-gray-100 `}>
							{Promotion}
						</h4>
						<p style={{ "fontFamily": `${fonts[index1].paragraphfont2}` }}
							className={`text-sm text-gray-100 `}>{Description} </p>
					</div>
					<div className="absolute bottom-2 left-0 px-6">
						<div className="relative">
							<h4 style={{ "fontFamily": `${fonts[index1].paragraphfont3}` }}
								className={`text-sm text-gray-100 max-w-[280px]`}>
								Graphic Generated By AI
							</h4>
							<p style={{ "fontFamily": `${fonts[index1].paragraphfont3}` }}
								className={`text-sm text-gray-100 max-w-[280px]`}>
								prompt: {prompt}
							</p>
						</div>
					</div>
					<div className="absolute right-0 bottom-0 p-2">
						<div className="flex items-center">
							<h4 style={{ "fontFamily": `${fonts[index1].paragraphfont3}` }}
								className={`text-[15px] text-lg font-semibold tracking-tight text-gray-100 `}>
								Contact at:
							</h4>
							<p style={{ "fontFamily": `${fonts[index1].paragraphfont3}` }}
								className={`text-[15px] text-lg font-normal text-gray-100 ml-2`}>{` ${Contact}`}</p>
						</div>
					</div>
				</div>
				<div className="z-20 absolute space-y-2 right-8 top-8">
					<div className="hidden group-hover:flex relative">
						<img className="absolute left-3 top-3" src={EditIcon} alt="Edit Icons" width="15px" height="15px" />
						<button className="py-2 pl-8 pr-4 text-white text-md font-roboto font-bold rounded bg-black" onClick={handleClick} >Edit</button>
					</div>

					
					{/* <div className="hidden group-hover:flex relative">
						<Preview/>
					</div> */}

					
					
					
					
				</div>
			</div> */}


			{
				index1 == 3 &&
				<div className="h-[1000px]">
					<div className="absolute bg-slate-100 border-b-2 top-0 left-[50%] translate-x-[-50%] p-4 shadow-[0px_22px_70px_4px_rgba(0,0,0,0.56)] rounded-lg mt-8">
						<div className="z-20 relative flex flex-col items-center align-center">
							<div className="w-[1080px] h-[1080px] top-6">
								<div className="absolute w-[1080px] h-[1080px] cursor-pointer">
									<img className="object-cover w-full h-full" src={data.image_path} alt="Flower and sky" />
									<div className="absolute top-0 left-0 px-6 py-12">
										<div className="relative">
											<h4 style={{ "fontFamily": `${fonts[index1].headingfont}` }}
												className={`mb-3 text-[48px] font-bold tracking-tight text-gray-100 max-w-[600px]`}
											>
												{Title}
											</h4>
											<p style={{ "fontFamily": `${fonts[index1].paragraphfont1}` }}
												className={`max-w-[600px]  text-[32px]  text-sm leading-normal text-gray-200`}>
												{posterText[index]}
											</p>
										</div>
									</div>
									<div className="absolute top-[50%] left-0 px-6">
										<h4 style={{ "fontFamily": `${fonts[index1].paragraphfont2}` }}
											className={`font-extrabold  text-[48px] text-gray-100 `}>
											{Promotion}
										</h4>
										<p style={{ "fontFamily": `${fonts[index1].paragraphfont2}` }}
											className={`text-sm text-gray-100 text-[32px] mt-2`}>{Description} </p>
									</div>
									<div className="absolute bottom-8 left-0 px-6">
										<div className="relative">
											<h4 style={{ "fontFamily": `${fonts[index1].paragraphfont3}` }}
												className={`text-sm text-[24px]  text-gray-100 max-w-[600px]`}>
												Graphic Generated By AI
											</h4>
											<p style={{ "fontFamily": `${fonts[index1].paragraphfont3}` }}
												className={`text-sm mt-2 text-[18px] text-gray-100 max-w-[600px]`}>
												prompt: {prompt}
											</p>
										</div>
									</div>
									<div className="absolute right-8 bottom-6">
										<div className="relative">
											<h4 style={{ "fontFamily": `${fonts[index1].paragraphfont3}` }}
												className={`text-[24px] text-lg tracking-tight text-gray-100`}>
												Contact at:
											</h4>
											<p style={{ "fontFamily": `${fonts[index1].paragraphfont3}` }}
												className={`text-[18px] text-lg font-normal text-gray-100`}>{` ${Contact}`}</p>
										</div>
									</div>
								</div>
							</div>
							<div className="flex w-full items-end justify-end gap-4 p-2 mb-4">
								<div className="relative">
									<img className="absolute left-3 top-3" src={EditIcon} alt="Edit Icons" width="15px" height="15px" />
									<button className="py-2 pl-8 pr-4 text-white text-md font-roboto font-bold rounded bg-black" onClick={handleClick} >Edit</button>
								</div>
								<div className="relative">
									<img className="absolute left-3 top-3 text-black" src={EditIcon} alt="Edit Icons" width="15px" height="15px" />
									<button className="py-2 pl-8 pr-4 text-white text-md font-roboto font-bold rounded bg-[#1976d2]" onClick={handleClick} >Publish</button>
								</div>
							</div>
						</div>

					</div>
				</div>			
			}

		</>
	)
}

export default templatePreview
